### PR TITLE
Make website interactive

### PR DESCRIPTION
**Pull request by seyioyemade**
## Make website interactive

In this milestone I:
- Added a new JavaScript file and import it as a module
- Added event listener to the checkbox (change).
- Updated items object's value for completed key upon user actions.
- Implemented a function for the "Clear all completed" button using filter() method).
- Stored the updated array of items in local storage, so the user gets the correct list of values after the page reloads (which means that any changes made to the list is preserved).

Please note that linters was disabled in some parts of my project yesterday because fixing them would break my code hugely. Kindly be lenient with me 🙏

### CODE REVIEW

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
Hi @seyioyemade,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

- [ ] please configer webpack properly cause when i run it im getting an error
- [ ] see screenshot below
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by seyioyemade** [comment]
@mwanawabangona 

Thank you for the review, but I'm very confused here, the project is running perfectly on my end.

And for the src, that's what is recommended in the document provided for reference by Microverse.
https://webpack.js.org/guides/getting-started/#basic-setup

Please help!

**Comment by mwanawabangona** [comment]
@seyioyemade can we do a zoom call??  please so you can show me

**Comment by seyioyemade** [comment]
@mwanawabangona 
Yes please. I can show you

**Review by mwanawabangona — APPROVED** [review]
Hi @seyioyemade ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  


## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
